App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = "App_Login"


urlpatterns = [
  path('signup/', views.signup, name='signup'),
  path('login/', views.login_page, name='login'),
  path('edit/', views.edit_profile, name='edit'),
  path('profile/',views.profile, name='profile'),
  path('logout/', views.user_logout, name='logout'),
  path('user/<username>/', views.user, name='user'),
  path('follow/<username>/', views.follow, name='follow'),
  path('unfollow/<username>/', views.unfollow, name='unfollow'),
    ]

My_Social_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
# from django.contrib.staticfiles.urls import static , staticfiles_urlpattern
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from App_Posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('posts/', include('App_Posts.urls')),
    path('', views.home, name='home'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user_profile")
    profile_pic = models.ImageField(upload_to='profile_pic', blank=True)
    description = models.TextField(blank=True)
    full_name = models.CharField(max_length=264, blank=True)
    dob = models.DateField(blank=True, null=True)
    website = models.URLField(blank=True)
    facebook = models.URLField(blank=True)

class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name="follower")
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")
    created_date = models.DateTimeField(auto_now_add=True)
    

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from App_Login.models import UserProfile




class CreateNewUser(UserCreationForm):
    email = forms.EmailField(required=True, label="", widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    username = forms.CharField(required=True, label="", widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password1 = forms.CharField(required=True, label="", widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(required=True, label="", widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))

    class Meta:
        model = User

        fields = ('email', 'username','password1', 'password2')


class EditProfile(forms.ModelForm):
    dob = forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model = UserProfile()        
        exclude = ('user',)

App_Login/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from App_Login.forms import CreateNewUser
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from App_Login.models import UserProfile
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from App_Login.models import UserProfile, Follow
from App_Login.forms import EditProfile
from App_Posts.forms import PostForm
from django.contrib.auth.models import User
# Create your views here.

def signup(request):
    form = CreateNewUser()
    registered = False
    if request.method == 'POST':
        form = CreateNewUser(data=request.POST)
        if form.is_valid():
            user = form.save()
            registered = True
            user_profile = UserProfile(user=user)
            user_profile.save()
            return HttpResponse(reverse('App_Login:login'))
    return render(request,'App_Login/signup.html', {'title': 'Signup . instagram','form': form})

def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('home'))

    return render(request,'App_Login/login.html', {'title': 'Login','form': form})

@login_required
def edit_profile(request):
    current_user = UserProfile.objects.get(user=request.user)
    form = EditProfile(instance=current_user)
    if request.method == 'POST':
        form = EditProfile(request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save(commit=True)
            form = EditProfile(instance=current_user)
            return HttpResponseRedirect(reverse('App_Login:profile'))

    return render(request,'App_Login/profile.html', {'title': 'Edit Profile', 'form': form})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:login'))


@login_required
def profile(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return HttpResponseRedirect(reverse('home'))
    return render(request, 'App_Login/user.html', context={'title':'User', 'form': form})



@login_required
def user(request, username):
    user_other = User.objects.get(username=username)
    already_followed = Follow.objects.filter(follower=request.user, following=user_other)
    if user_other == request.user:
        return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/user_other.html', context={'user_other': user_other, 'already_followed':already_followed})


@login_required
def follow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects.filter(follower=follower_user, following=following_user)
    if not already_followed:
        follower_user = Follow(follower=follower_user, following=following_user)
        follower_user.save()
    return HttpResponseRedirect(reverse('App_Login:user', kwargs={'username': username}))






@login_required
def unfollow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects.filter(follower=follower_user, following=following_user)
    already_followed.delete()
    return HttpResponseRedirect(reverse('App_Login:user', kwargs={'username': username}))

templates/App_Login/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title_block %} {{title}} {% endblock %}

{% block css_block %}
<style>
    .sign_up {
      width: 550px;
      border: 1px solid #ccc;
      padding: 25px;
    }
    .log_in {
      width: 550px;
      padding: 40px;
      border: 1px solid #ccc;
    }
  </style>
{% endblock %}

{% block body_block %}
<center>
<div class='log_in'>
    <form method='POST'>
        {{form|crispy}}
        {% csrf_token %}
        <button type="submit" style="width:100%" class="btn btn-primary">Login</button>
    </form>
</div>
<br>
<div class="sign_up">
    <p> Don't have an account? <a href="{% url 'App_Login:signup' %}">Sign up</a></p>
</div>
</center>
{% endblock %}

templates/App_Login/profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{%block title_block%}{{title}}{%endblock%}
{%block css_block%}

{%endblock%}
{%block body_block%}
<form method="POST" enctype="multipart/form-data">
  {{form|crispy}}
  {% csrf_token %}
  <button type="submit" name="button" class='btn btn-primary'>Submit</button>
</form>
{% endblock %}

templates/App_Login/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %} 
{% block title_block %} {{title}} {% endblock %}

{% block css_block %}
<style>
    .sign_up {
      width: 550px;
      border: 1px solid #ccc;
      padding: 40px;
    }
    .log_in {
      width: 550px;
      padding: 25px;
      border: 1px solid #ccc;
    }
  </style>
{% endblock %}
{% block body_block %}
    <center>
        <div class='sign_up'>
            <h3>Sign up to see photos from your friends.</h3>
            <form method="POST">
                {{ form|crispy}}
                
                {% csrf_token %}
                <button type="submit" style="width:100%" class="btn btn-primary" >Signup</button>
            </form>
        </div>
        <br>
        <div class="log_in">
            <p>Have you an account? <a href="{% url 'App_Login:login' %}">Login</a></p>
        </div>
    </center>
{% endblock %}

templates/App_Login/user.html
{% extends 'navbar.html' %}
{%block title_block %} {{user.user_profile.full_name}} (@{{user.username}}) {%endblock%}
{%block css_block%}
<style>
  .crop {
    width: 200px;
    height: 200px;
    overflow: hidden;
  }

  .crop img {
    width: 400px;
    height: 300px;
    margin: -75px 0 0 -100px;
  }
</style>
{% endblock%}

{%block body_block%}
<div class="row">
  <div class="col-sm-4">
    {% if user.user_profile.profile_pic %}
    <img src="/media/{{user.user_profile.profile_pic}}" width="250px" height="250px" class="rounded-circle">
    {% else %}
    <img src="/media/save-commentor-pic.jpeg" width="250px" height="250px" class="rounded-circle">
    {% endif %}
  </div>
  <div class="col-sm-8">
    <h1>{{user.username}} &nbsp; <a href="{% url 'App_Login:edit' %}" class="btn btn-light">Edit Profile</a></h1>
    <br>
    <h4>{{user.post.count}} posts &nbsp; &nbsp; {{user.following.count}} followers &nbsp; &nbsp; {{user.follower.count}} following</h4>
    <br>
    <h3>{{user.user_profile.full_name}}</h3>
    <p>{{user.user_profile.description|linebreaks}}</p>
  </div>
</div>
<hr>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
  New Post
</button> 
<br>
<br>

<!-- The Modal -->
<div class="modal" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
    
      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Post a photo</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      
      <!-- Modal body -->
      <div class="modal-body">
        
        <form method='POST' enctype='multipart/form-data'>
          {{form.as_p}}
          {% csrf_token %}
          <button type="submit"  class='btn btn-primary'>Post</button>
        </form>
      </div>
      
      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
      
    </div>
  </div>
</div>

<div class='row'>
  {% for post in user.post.all %}
  <div class='crop'>
    <img src="/media/{{post.image}}" title='{{post.caption}}'>
  </div> 
  {% endfor %}
</div>

</div>



{%endblock%}

templates/App_Login/user_other.html
{% extends 'navbar.html' %}
{%block title_block %} {{user.user_profile.full_name}} (@{{user.username}}) {%endblock%}
{%block css_block%}
<style>
  .crop {
    width: 200px;
    height: 200px;
    overflow: hidden;
  }

  .crop img {
    width: 400px;
    height: 300px;
    margin: -75px 0 0 -100px;
  }
</style>
{% endblock%}

{%block body_block%}
<div class="row">
  <div class="col-sm-4">
    {% if user_other.user_profile.profile_pic %}
    <img src="/media/{{user_other.user_profile.profile_pic}}" width="250px" height="250px" class="rounded-circle">
    {% else %}
    <img src="/media/save-commentor-pic.jpeg" width="250px" height="250px" class="rounded-circle">
    {% endif %}
  </div>
  <div class="col-sm-8">
    <h1>{{user_other.username}} &nbsp; 
      {% if not already_followed %}
      <a href='{% url 'App_Login:follow' username=user_other.username %}' class='btn btn-primary'>Follow</a>  
      {% else %}
      <a href='{% url 'App_Login:unfollow' username=user_other.username %}' class='btn btn-primary'>Unfollow</a>  
      {% endif %}
    </h1>
    <h4>{{user_other.post.count}} posts &nbsp; &nbsp; {{user_other.following.count}} followers &nbsp; &nbsp; {{user_other.follower.count}} following</h4>
    <br>
    <h3>{{user_other.user_profile.full_name}}</h3>
    <p>{{user_other.user_profile.description|linebreaks}}</p>
  </div>
</div>
<hr>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
  New Post
</button> 
<br>
<br>

<div class='row'>
  {% for post in user_other.post.all %}
  <div class='crop'>
    <img src="/media/{{post.image}}" title='{{post.caption}}'>
  </div> 
  {% endfor %}
</div>

</div>



{%endblock%}