App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = "App_Login"


urlpatterns = [
  path('signup/', views.signup, name='signup'),
  path('login/', views.login_page, name='login'),
  path('edit/', views.edit_profile, name='edit'),
  path('profile/',views.profile, name='profile'),
  path('logout/', views.user_logout, name='logout'),
  path('user/<username>/', views.user, name='user'),
  path('follow/<username>/', views.follow, name='follow'),
  path('unfollow/<username>/', views.unfollow, name='unfollow'),
    ]

App_Posts/urls.py
from django.urls import path
from App_Posts import views

app_name = 'App_Posts'


urlpatterns = [
    path('', views.home, name='home'),
    path('like/<pk>/', views.liked, name='liked'),
    path('unlike/<pk>/', views.unliked, name='unliked'),
]

My_Social_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
# from django.contrib.staticfiles.urls import static , staticfiles_urlpattern
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from App_Posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('posts/', include('App_Posts.urls')),
    path('', views.home, name='home'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>

  <meta charset="utf-8">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  {% block title_block %} Signup {%endblock%}
  
  {% block css_block %} 

  {% endblock %}
</head>

<body>
    <div class="container" style="padding-top:20px">
        {% block body_block %}
        
        {% endblock %}
    </div>

</body>

templates/navabr.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>

  <meta charset="utf-8">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  {% block title_block %} Signup {%endblock%}
  
  {% block css_block %} 

  {% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-light navbar-light">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url '#' %}">#</a>
          </li>

        </ul>
      </nav>
    <div class="container" style="padding-top:20px">
        {% block body_block %}
        
        {% endblock %}
    </div>

</body>

templates/navbar.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>

  <meta charset="utf-8">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  {% comment %} {% block title_block %} Home Page {%endblock%} {% endcomment %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  
  {% block css_block %} 

  {% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-light navbar-light">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'App_Posts:home' %}">Home</a>
          </li>
          <form class="form-inline" method='GET'>
            <input class="form-control mr-sm-2" name='search' type="text" placeholder="Search">
            <button class="btn btn-success" type="submit">Search</button>
          </form>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'App_Login:logout' %}">Logout</a>
          </li>
          {% if user.user_profile.profile_pic %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'App_Login:profile' %}" width='40px' height='40px' class='rounded-circle' ><img src='/media/{{user.user_profile.profile_pic}}' width='40px' height='40px' class='rounded-circle'></a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'App_Login:profile' %}" ><img src='/media/save-commentor-pic.jpeg' width='40px' height='40px' class='rounded-circle'></a>
          </li>
          {% endif %}
          
        </ul>
      </nav>
    <div class="container" style="padding-top:20px">
        {% block body_block %}
        
        {% endblock %}
    </div>

</body>