App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = "App_Login"


urlpatterns = [
  path('signup/', views.signup, name='signup'),
  path('login/', views.login_page, name='login'),
  path('edit/', views.edit_profile, name='edit'),
  path('profile/',views.profile, name='profile'),
  path('logout/', views.user_logout, name='logout'),
  path('user/<username>/', views.user, name='user'),
  path('follow/<username>/', views.follow, name='follow'),
  path('unfollow/<username>/', views.unfollow, name='unfollow'),
    ]

App_Posts/urls.py
from django.urls import path
from App_Posts import views

app_name = 'App_Posts'


urlpatterns = [
    path('', views.home, name='home'),
    path('like/<pk>/', views.liked, name='liked'),
    path('unlike/<pk>/', views.unliked, name='unliked'),
]

My_Social_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
# from django.contrib.staticfiles.urls import static , staticfiles_urlpattern
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from App_Posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('posts/', include('App_Posts.urls')),
    path('', views.home, name='home'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Posts/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    image = models.ImageField(upload_to='post_images', blank=True, null=True)
    caption = models.CharField(max_length=264, blank=True, null=True)
    upload_date = models.DateTimeField(auto_now_add=True)
    upload_date = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ['-upload_date']

class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='liked_post')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker')
    date_created = models.DateTimeField(auto_now_add=True)

App_Posts/forms.py
from django import forms
from App_Posts.models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['image', 'caption',]

App_Posts/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from App_Posts.models import Post, User, Like
from App_Login.models import Follow
# Create your views here.


@login_required
def home(request):
    following_list = Follow.objects.filter(follower=request.user)
    posts = Post.objects.filter(author__in=following_list.values_list('following'))
    liked_post = Like.objects.filter(user=request.user)

    liked_post_list = liked_post.values_list('post', flat=True)
    print(liked_post_list)
    if request.method == 'GET':
        search = request.GET.get('search', '')
        result = User.objects.filter(username__icontains=search)
    return render(request, 'App_Posts/home.html', context={
        'title': 'Home', 
        'search': search, 
        'result': result,
        'posts': posts,
        'liked_post_list':liked_post_list
        })

@login_required
def liked(request, pk):
    post = Post.objects.get(pk=pk)
    already_liked = Like.objects.filter(post=post,user=request.user)
    if not already_liked:
        liked_post = Like(post=post ,user=request.user)
        liked_post.save()

    return HttpResponseRedirect(reverse('home'))


@login_required
def unliked(request, pk):
    post = Post.objects.get(pk=pk)
    already_liked = Like.objects.filter(post=post,user=request.user)
    already_liked.delete()
    
    return HttpResponseRedirect(reverse('home'))

templates/App_Posts/home.html
{% extends "navbar.html" %}
{% comment %} {%block title_block %} {{title}} {%endblock%} {% endcomment %}

<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
{% block body_block %}
    {% if search %}
        {% for user in result %}
            <div class="row">
                <div class="col-sm-2">
                    {% if user.user_profile.profile_pic %}
                        <img src='/media/{{user.user_profile.profile_pic}}' width='75px' height='75px' class='rounded-circle'>
                    {% else %}
                        <img src='/media/save-commentor-pic.jpeg' width='75px' height='75px' class='rounded-circle'>
                    {% endif %}
                </div>
                <div class="col-sm-10">
                    <a href='{% url 'App_Login:user' username=user.username %}'>{{user.username}}</a>
                    <br>
                    {{user.user_profile.full_name}}
                </div>
            </div>
        {% endfor %}
    {% else %}
    <div class="row">
        <div class="col-sm-8">
        {% for post in posts %}
            <div style='border: 1px solid #888888'>
                <div style='padding: 10px'>
                    {% if post.author.user_profile.profile_pic %}
                        <img src='/media/{{post.author.user_profile.profile_pic}}' width='40px' height='40px' class='rounded-circle'>
                    {% else %}
                        <img src='/media/save-commentor-pic.jpeg' width='40px' height='40px' class='rounded-circle'>
                    {% endif %}
                    <a href='{% url 'App_Login:user' username=post.author %}'>{{ post.author }}</a>
                    <br>
                    <br>
                    <img src='/media/{{post.image}}' width='100%'>
                    <div style="padding:20px">
                        {{post.caption}}<br>
                        {{ post.liked_post.count }} Likes <br>
                        {% if post.pk in liked_post_list %}
                        <a href="{% url 'App_Posts:unliked' pk=post.pk %}"><i class="fa fa-heart" style="font-size:36px"></i></a>
                        {% else %}
                        <a href="{% url 'App_Posts:liked' pk=post.pk %}"><i class="fa fa-heart-o" style="font-size:36px"></i></a>
                        {% endif %}
                      </div>
                </div>
            </div>

        {% endfor %}
     
        </div>
        <div class="col-sm-4">
            <div class="row">
                <div class="col-sm-4">
                    {% if user.user_profile.profile_pic %}
                        <img src='/media/{{user.user_profile.profile_pic}}' width='75px' height='75px' class='rounded-circle'>
                    {% else %}
                        <img src='/media/save-commentor-pic.jpeg' width='75px' height='75px' class='rounded-circle'>
                    {% endif %}
                </div>
                <div class="col-sm-4">
                    {{ user.username}}
                    <br>
                    {{user.user_profile.full_name}}
                </div>
            </div>
        </div>
    </div>
      
    {% endif %}
{% endblock %}